name: AuthenticatorTests

on: [push]

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: List Xcode versions
        run: ls -n /Applications/ | grep Xcode*
      - name: Show Xcode version and simulators
        run: xcode-select -p; xcodebuild -version; xcrun simctl list
      - name: Test on emulator
        run: xcodebuild clean test -sdk iphonesimulator -project Authenticator.xcodeproj -scheme Authenticator -destination "platform=iOS Simulator,OS=latest,name=iPhone Xs" | xcpretty --test --color && exit ${PIPESTATUS[0]}
