name: AuthenticatorTests

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test on emulator
        run: xcodebuild clean test -sdk iphonesimulator -workspace Authenticator.xcworkspace -scheme AuthenticatorTests -destination "platform=iOS Simulator,OS=13.3,name=iPhone 12" | xcpretty --test --color && exit ${PIPESTATUS[0]}
