name: AuthenticatorTests

on: [push]
env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test on emulator
        run: ls $DEVELOPER_DIR; xcodebuild -version; xcodebuild clean test -sdk iphonesimulator -project Authenticator.xcodeproj -scheme Authenticator -destination "platform=iOS Simulator,OS=14.7,name=iPhone 12" | xcpretty --test --color && exit ${PIPESTATUS[0]}

